---
name: chumanter
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.3.2
  assets_audio_player: ^3.0.0
  provider: ^6.0.5
  another_flushbar: ^1.12.30
  pinput: ^3.0.0
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  qr_code_scanner: ^1.0.1
  carousel_slider: ^4.2.1
  circular_seek_bar: ^1.1.0+2
  flutter_svg: ^2.0.7
  step_progress_indicator: ^1.0.2
  loading_overlay: ^0.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_multi_formatter: ^2.11.11
  bottom_picker: ^2.1.0
  csc_picker: ^0.2.7
  google_fonts: ^6.1.0
  dropdown_textfield: ^1.0.8
  appinio_video_player: ^1.2.2
  easy_localization: ^3.0.3
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  permission_handler: ^11.0.1
  animations: ^2.0.8
  progress_dialog_null_safe: ^1.0.7
  intl: ^0.19.0
  image_picker: ^1.0.4
  restart_app: ^1.2.1
  chewie: ^1.7.4
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  alt_sms_autofill: ^1.0.0
  expandable_page_view: ^1.0.17
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.1
  skeletonizer: ^1.0.1
  easy_stepper: ^0.8.3
  showcaseview: ^2.0.3
  fadingpageview: ^1.0.0
  keep_screen_on: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/views/language/
    - assets/images/
    - assets/videos/
    - assets/fonts/
    - assets/json/
    - assets/svg/
    - shorebird.yaml
  fonts:
    - family: RalewayBold
      fonts:
        - asset: assets/fonts/Raleway-ExtraBold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Raleway Medium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
